const SEED_DATA=[
{c:"Control Risks",t:"security",w:"controlrisks.com",l:"London",co:"UK",p:"hot",n:"Global leader. EP Analyst roles. 1001-5000 employees. Careers: controlrisks.com/careers"},
{c:"GardaWorld",t:"security",w:"gardaworld.com",l:"Montreal",co:"Canada",p:"hot",n:"World's largest private security. 463 EP jobs. Portal: jobs.garda.com/go/International-Jobs/7695900/"},
{c:"Constellis",t:"security",w:"constellis.com",l:"Herndon, VA",co:"USA",p:"hot",n:"Military Friendly Gold 2026. 8700+ staff. 50 countries. EP Agent $54-88K. Careers: constellis.com/careers/"},
{c:"Pilgrims Group",t:"security",w:"pilgrimsgroup.com",l:"Woking, Surrey",co:"UK",p:"hot",n:"Active CPO recruitment. Ex-military core. Email: info@pilgrims-rmg.com"},
{c:"ETS Risk Management",t:"security",w:"ets-riskmanagement.com",l:"Bethesda/London",co:"USA",p:"hot",n:"Elite boutique. Leadership from SAS/SRR/MI5. 80+ countries. Recruits via network/LinkedIn"},
{c:"Neptune P2P Group",t:"security",w:"neptunep2pgroup.com",l:"Dubai/Manchester",co:"UAE",p:"hot",n:"FOUNDED by British+French SF. Legion = direct cultural match. +971 45 770 391"},
{c:"Allied Universal / G4S",t:"security",w:"aus.com",l:"Santa Ana/London",co:"USA/UK",p:"medium",n:"800K+ employees. EP $58-184K. Portal: jobs.aus.com"},
{c:"Ambrey",t:"security",w:"ambrey.com",l:"Hereford",co:"UK",p:"medium",n:"Leading PMSC. 1000+ guards. Maritime + land. Careers: ambrey.com/careers/"},
{c:"Blue Mountain Group",t:"security",w:"bluemountaingroup.co.uk",l:"Carmarthen, Wales",co:"UK",p:"medium",n:"Discreet CP. ISO-accredited. WhatsApp network for graduates"},
{c:"Salama Fikira / SF Group",t:"security",w:"salamafikira.com",l:"Nottingham/Nairobi",co:"UK/Kenya",p:"medium",n:"Africa specialist (80%+). Mining, oil/gas. Hundreds of ex-Armed Forces"},
{c:"Black Swan UK",t:"security",w:"blackswanuk.com",l:"UK",co:"UK",p:"medium",n:"CP for executives, HNWI. RST. Intelligence-led. Referral-based"},
{c:"International SOS",t:"security",w:"internationalsos.com",l:"Singapore/London",co:"Singapore",p:"medium",n:"13,000+ experts. 81 security jobs. Careers: careers.internationalsos.com"},
{c:"Northcott Global Solutions",t:"security",w:"northcottglobalsolutions.com",l:"London",co:"UK",p:"medium",n:"CP bodyguard, evacuations. 49 employees. Email: info@northcottglobalsolutions.com"},
{c:"Solace Global",t:"security",w:"solaceglobal.com",l:"Poole, Dorset",co:"UK",p:"medium",n:"Maritime + HNWI. 400+ from EU Military/SF. Careers: solaceglobal.com/careers-at-solace-global/"},
{c:"Westminster Security",t:"security",w:"westminstersecurity.co.uk",l:"London",co:"UK",p:"hot",n:"Royals, heads of state, HNWI. 5+ years EP + military. NEVER call to follow up. Register: westminstersecurity.co.uk/recruitment/"},
{c:"AS Solution",t:"security",w:"careers.assolution.com",l:"Copenhagen",co:"Denmark",p:"hot",n:"Corporate EP. 86 countries. 501-1000 employees. Paid EP training. Portal"},
{c:"Gavin de Becker & Associates",t:"security",w:"gdba.com",l:"Los Angeles",co:"USA",p:"hot",n:"THE GOLD STANDARD. 49 positions. $75-130K. Careers: gdba.com/join-our-team"},
{c:"TorchStone Global",t:"security",w:"torchstoneglobal.com",l:"Arlington, VA",co:"USA",p:"hot",n:"Elite boutique. Sr Security Manager $126K. Careers: torchstoneglobal.com/contact-us/careers/"},
{c:"Hillard Heintze",t:"security",w:"hillardheintze.com",l:"Chicago",co:"USA",p:"medium",n:"Jensen Hughes. Recruits Secret Service, FBI, military. Careers: hillardheintze.com/careers/"},
{c:"Pinkerton",t:"security",w:"pinkerton.com",l:"Ann Arbor, MI",co:"USA",p:"medium",n:"Founded 1850. 41 jobs, 15 EP Specialist. Careers: pinkerton.com/careers/current-openings"},
{c:"Guidepost Solutions",t:"security",w:"guidepostsolutions.com",l:"New York",co:"USA",p:"medium",n:"VP Protective Services role. 17+ cities globally. Careers: guidepostsolutions.com/careers/"},
{c:"World Protection Group",t:"security",w:"worldprotectiongroup.com",l:"Beverly Hills",co:"USA",p:"medium",n:"Celebrities, politicians, CEOs. 200+ staff. Careers: worldprotectiongroup.com/jobs/"},
{c:"Royal Falcon Security",t:"security",w:"royalfalconsecurity.ae",l:"Abu Dhabi",co:"UAE",p:"hot",n:"FOUNDED by UAE royals. Direct match for royal family protection. Careers: royalfalconsecurity.ae/careers.html"},
{c:"Septimius Security",t:"security",w:"septimiussecurity.com",l:"Dubai",co:"UAE",p:"hot",n:"520+ operators. UHNWI, diplomats. SIRA-licensed. Multilingual valued. Jobs: septimiussecurity.com/jobs/"},
{c:"Falcon Shield Security",t:"security",w:"falcon-uae.ae",l:"Dubai",co:"UAE",p:"medium",n:"SIRA-approved. EP, CP, event security"},
{c:"ISF Global Solutions",t:"security",w:"isf-security-ae.com",l:"Dubai",co:"UAE",p:"medium",n:"High-end CP for UHNWI. 20+ years experience"},
{c:"PGS Solution",t:"security",w:"pgs-solution.com",l:"Dubai",co:"UAE",p:"medium",n:"25+ years. EP for celebrities, government, HNWI. SIRA-licensed"},
{c:"Sultan Royal Security",t:"security",w:"sultanroyalsecurity.com",l:"UAE",co:"UAE",p:"medium",n:"VIP protection. Royal/diplomatic focus. Careers: sultanroyalsecurity.com/career/"},
{c:"VCP Global Security",t:"security",w:"vcp-global.com",l:"Dubai",co:"UAE",p:"medium",n:"CP for UHNW families in UAE"},
{c:"NEOM",t:"security",w:"neom.com",l:"NEOM",co:"Saudi Arabia",p:"medium",n:"Saudi mega-project. 230+ security roles. Long-term contracts. Careers: neom.com/en-us/careers"},
{c:"Diaplous",t:"security",w:"diaplous.com",l:"Piraeus",co:"Greece",p:"medium",n:"Maritime risk management. 560+ clients. 6 international offices"},
{c:"Solutions Group Intl (SGI)",t:"management",w:"solutionsgroupinternational.com",l:"USA",co:"USA",p:"hot",n:"DIRECTLY hires CPO for tours. Green Day, Rihanna. US State Dept provider. Military veteran pipeline"},
{c:"T&M Protection Resources",t:"management",w:"tmusallc.com",l:"New York",co:"USA",p:"hot",n:"$45-55/hr. Actively hiring EP agents. Military/LE. Careers: tmusallc.com/careers/executive-protection-agent"},
{c:"Force Protection Agency",t:"management",w:"forceprotectionagency.com",l:"USA",co:"USA",p:"hot",n:"Music industry's biggest names. Military officer-led. Careers: forceprotectionagency.com/careers/"},
{c:"Insite Risk Management",t:"management",w:"insiteriskmanagement.com",l:"New York",co:"USA",p:"hot",n:"Celebrity, dignitary, sovereign protection. Email: info@insitesecurity.com"},
{c:"UKSPS International",t:"management",w:"ukspsinternational.com",l:"UK",co:"UK",p:"hot",n:"Dedicated music industry security division"},
{c:"VIS Protection",t:"management",w:"visprotection.com",l:"London/Dublin",co:"UK",p:"medium",n:"Celebrity/VIP bodyguard. Ex-military/police"},
{c:"ShowSec",t:"management",w:"showsec.co.uk",l:"UK",co:"UK",p:"medium",n:"35+ years. 450+ venues. More crowd mgmt than CPO. Foot in door. Careers: showsec.co.uk/jobs/"},
{c:"Warner Music Group",t:"management",w:"wmg.com",l:"New York",co:"USA",p:"hot",n:"ACTIVE Operations Security Manager role. Ed Sheeran, Dua Lipa. Portal: wmg.wd1.myworkdayjobs.com/WMGUS"},
{c:"Live Nation",t:"management",w:"livenationentertainment.com",l:"Beverly Hills",co:"USA",p:"hot",n:"World's largest live entertainment. 1446 jobs. Search director-level security"},
{c:"AEG Presents",t:"management",w:"aegpresents.com",l:"Los Angeles",co:"USA",p:"hot",n:"#2 globally. Dedicated Security & Safety category. Portal: aegworldwide.com/careers/job-search"},
{c:"Roc Nation",t:"management",w:"rocnation.com",l:"New York",co:"USA",p:"hot",n:"Jay-Z. Rihanna, J. Cole. Highest-profile clients. Email: info@rocnation.com"},
{c:"Full Stop Management",t:"management",w:"fullstopmgmt.com",l:"Los Angeles",co:"USA",p:"hot",n:"Harry Styles, Eagles, Cardi B. Irving Azoff. Email: info@fullstopmgmt.com"},
{c:"Maverick Management",t:"management",w:"maverick.com",l:"Beverly Hills",co:"USA",p:"hot",n:"Madonna, U2, The Weeknd, RHCP. Guy Oseary. Massive tours"},
{c:"WME",t:"management",w:"wmeagency.com",l:"Beverly Hills",co:"USA",p:"medium",n:"World's largest talent agency. Endeavor/UFC. Uses external CPO. Networking target"},
{c:"CAA",t:"management",w:"caa.com",l:"Los Angeles",co:"USA",p:"medium",n:"#1 full-service agency. 3000+ athletes. Uses contract CP"},
{c:"Wasserman / THE TEAM",t:"management",w:"the.team",l:"Los Angeles",co:"USA",p:"medium",n:"Music + Sports. 65 cities, 27 countries. Email: hello@the.team"},
{c:"YMU Group",t:"management",w:"ymugroup.com",l:"London",co:"UK",p:"medium",n:"Entertainment, sport. Email: Careers@ymugroup.com"},
{c:"TaP Music",t:"management",w:"tap-music.com",l:"London",co:"UK",p:"medium",n:"Lana Del Rey, Ellie Goulding. Contract CP for tours"},
{c:"Greycoat Lumleys",t:"agency",w:"greycoatlumleys.co.uk",l:"London",co:"UK",p:"hot",n:"25+ years. Dedicated security division. Elite military preferred. Email: info@greycoatlumleys.co.uk"},
{c:"Tiger Recruitment",t:"agency",w:"tiger-recruitment.com",l:"London/Dubai",co:"UK",p:"hot",n:"B Corp. Dedicated CP division. UHNWI, diplomats, royals. Email: info@tiger-recruitment.co.uk"},
{c:"Polo & Tweed",t:"agency",w:"poloandtweed.com",l:"London, Mayfair",co:"UK",p:"hot",n:"A-listers, royals, Middle East royals. 14K+ candidates. 40-71K+ GBP. Tel: +44 203 858 0233"},
{c:"Oplu",t:"agency",w:"oplu.com",l:"London, Mayfair",co:"UK",p:"hot",n:"UHNW family office. Explicitly Head of Security / CP Manager. Email: hello@oplu.com"},
{c:"Bespoke Britannia Security",t:"agency",w:"bespokebritanniasecurity.co.uk",l:"London, Mayfair",co:"UK",p:"hot",n:"20+ years British Royal Household. 30+ years Security Intelligence."},
{c:"Intelligent Protection Intl",t:"agency",w:"intelligent-protection.co.uk",l:"London/Paris/Geneva",co:"UK",p:"hot",n:"Middle East royal family since 2017. Seeks bi/trilingual with Royal Protection. PERFECT FIT. Email: info@intelligent-protection.co.uk"},
{c:"Infinite Risks",t:"agency",w:"infiniterisks.com",l:"Amsterdam",co:"Netherlands",p:"hot",n:"Royal families in 50+ countries. Email: contact@infiniterisks.com | +31 20 301 1395"},
{c:"CourtesyMasters",t:"agency",w:"courtesymasters.com",l:"The Hague",co:"Netherlands",p:"hot",n:"CPO for royal households, UHNWI. Email: info@courtesymasters.com"},
{c:"Morgan & Mallet",t:"agency",w:"householdstaff.agency",l:"Monaco/Dubai/NYC",co:"International",p:"hot",n:"1200+ placements/year. 4100+ security pros in Switzerland. Residential security division"},
{c:"Talent Gurus",t:"agency",w:"talent-gurus.com",l:"USA/London/Miami",co:"USA",p:"hot",n:"Head of Security UHNW. $140K-$350K+. Retained search under NDA. 12-18 weeks"},
{c:"Heritage Staffing",t:"agency",w:"heritage-staffing.ch",l:"Geneva",co:"Switzerland",p:"hot",n:"SECO-licensed. 15+ years UHNW. Bodyguards, drivers. Email: info@heritage-staffing.ch"},
{c:"GulfTalent",t:"agency",w:"gulftalent.com",l:"UAE",co:"UAE",p:"hot",n:"Leading ME job board. Active CPO listings. Western European ex-mil preferred"},
{c:"Guildhall",t:"agency",w:"Via GulfTalent",l:"UAE",co:"UAE",p:"hot",n:"Executive search MENA. Actively hiring CPO/bodyguard for high-profile Dubai client"},
{c:"Close Career",t:"agency",w:"closecareer.com",l:"UAE",co:"UAE",p:"medium",n:"UAE royal guard recruitment. Email: jobs@closecareer.com"},
{c:"Norsk Tactical",t:"agency",w:"norsktactical.co.uk",l:"Scotland/UK",co:"UK",p:"medium",n:"UHNWI, politicians, embassy work. SIA-licensed. Careers: norsktactical.co.uk/vacancies"},
{c:"MyStaffHQ",t:"agency",w:"mystaffhq.com",l:"Online",co:"UK",p:"medium",n:"Elite private staff jobs. CP section: mystaffhq.com/jobs/close-protection-security"},
{c:"Silver Swan Recruitment",t:"agency",w:"silverswanrecruitment.com",l:"London/Miami/Dubai",co:"UK",p:"medium",n:"UHNW families globally. Estate managers, yacht crew"},
{c:"UNDSS (UN)",t:"security",w:"un.org",l:"New York",co:"USA",p:"hot",n:"CP for senior UN officials in 131 countries. Pass Security Officer Test (SOT). Portal: careers.un.org"},
{c:"EU CSDP Missions",t:"security",w:"eeas.europa.eu",l:"Brussels",co:"Belgium",p:"hot",n:"70+ vacancies 2026! Norway seconds actively. Contact Norwegian MFA."},
{c:"NATO HQ",t:"security",w:"nato.int",l:"Brussels",co:"Belgium",p:"hot",n:"Norwegian = eligible. Royal Guard = directly relevant. NATO SECRET via NSM. Portal: nato.taleo.net"},
{c:"OSCE",t:"security",w:"osce.org",l:"Vienna",co:"Austria",p:"hot",n:"Mission Security Officer + Field Security Officer ACTIVE now! Portal: jobs.osce.org"},
{c:"UNHCR",t:"security",w:"unhcr.org",l:"Geneva",co:"Switzerland",p:"hot",n:"Field security in high-risk environments. Portal: unhcr.wd3.myworkdayjobs.com/External"},
{c:"WFP",t:"security",w:"wfp.org",l:"Rome",co:"Italy",p:"hot",n:"Multiple security positions: Beirut, Cairo, Ukraine, South Sudan. Portal: wfp.org/careers"},
{c:"GardaWorld Federal Services",t:"security",w:"garda-federal.com",l:"Washington DC",co:"USA",p:"hot",n:"Embassy security globally. 13 positions. Accessible to non-US. Portal: jobs.garda.com"},
{c:"NRC",t:"security",w:"nrc.no",l:"Oslo",co:"Norway",p:"hot",n:"NORWEGIAN org = major advantage. Field: Palestine, Goma, Kyiv, Myanmar. Portal: nrc.no/careers"},
{c:"ICRC",t:"security",w:"icrc.org",l:"Geneva",co:"Switzerland",p:"hot",n:"Conflict zones. Armed Forces Delegate role. Legion = strong asset. Portal: careers.icrc.org"},
{c:"TotalEnergies",t:"security",w:"totalenergies.com",l:"Paris",co:"France",p:"hot",n:"FRENCH company! Legion = massive advantage. Nigeria, Angola, Mozambique, Libya, Iraq. Portal: careers.totalenergies.com"},
{c:"Amentum (ex-DynCorp)",t:"security",w:"amentum.com",l:"Germantown, MD",co:"USA",p:"medium",n:"34,000 employees in 105 countries. US-focused. Careers: amentum.com/careers/"},
{c:"EEAS",t:"security",w:"eeas.europa.eu",l:"Brussels",co:"Belgium",p:"medium",n:"4 open positions. EU citizenship may be required. Check EEA eligibility"},
{c:"Frontex",t:"security",w:"frontex.europa.eu",l:"Warsaw",co:"Poland",p:"medium",n:"Up to 400 officers in 2025-2026. More border guard than CP. Careers: frontex.europa.eu/careers/"},
{c:"SHAPE (NATO)",t:"security",w:"shape.nato.int",l:"Mons",co:"Belgium",p:"medium",n:"Security Officer roles. Via NATO Taleo"},
{c:"MSF",t:"security",w:"msf.org",l:"Geneva",co:"Switzerland",p:"medium",n:"Security Advisor. Requires humanitarian experience + military. Portal: msf.org/jobs"},
{c:"Save the Children",t:"security",w:"savethechildren.net",l:"London",co:"UK",p:"medium",n:"157+ positions. Security management. Portal: savethechildren.net/careers/apply"},
{c:"Oxfam",t:"security",w:"oxfam.org",l:"Nairobi",co:"Kenya",p:"medium",n:"50+ positions 2026. Security Manager active. $40-120K+. Portal: jobs.oxfam.org.uk"},
{c:"IRC",t:"security",w:"rescue.org",l:"New York",co:"USA",p:"medium",n:"Dedicated Safety & Security career track. Portal: careers.rescue.org/us/en/c/safety-security-jobs"},
{c:"BP",t:"security",w:"bp.com",l:"London",co:"UK",p:"medium",n:"Iraq, Azerbaijan, Algeria. Corporate Security. Portal: bp.com/en/global/corporate/careers.html"},
{c:"Shell",t:"security",w:"shell.com",l:"London",co:"UK",p:"medium",n:"Nigeria, Iraq, Oman. Security Manager roles. Portal: shell.com/careers"},
{c:"ExxonMobil",t:"security",w:"corporate.exxonmobil.com",l:"Spring, TX",co:"USA",p:"medium",n:"Guyana, Papua NG, Mozambique, Iraq. Portal: jobs.exxonmobil.com"},
{c:"Rio Tinto",t:"security",w:"riotinto.com",l:"London/Melbourne",co:"UK/Australia",p:"medium",n:"Guinea, Madagascar, South Africa, Mongolia. 39 positions. Portal: jobs.riotinto.com"},
{c:"Glencore",t:"security",w:"glencore.com",l:"Baar",co:"Switzerland",p:"medium",n:"DRC (Katanga), Chad, Cameroon, Colombia. Portal: glencore.com/careers"},
// === JOB LISTINGS ===
{c:"Silent Professionals \u2014 Corporate EP Agent",t:"security",w:"silentprofessionals.org/jobs/corporate-executive-protection-agent-dallas/",l:"Dallas, TX",co:"USA",p:"hot",n:"$133K/yr + bonus + benefits. Full-time. ACTIVE LISTING.",j:1},
{c:"Silent Professionals \u2014 Corporate EP Agent",t:"security",w:"silentprofessionals.org/jobs/corporate-executive-protection-agent-chicago/",l:"Chicago, IL",co:"USA",p:"hot",n:"$133K/yr + bonus + benefits. Full-time. ACTIVE LISTING.",j:1},
{c:"Silent Professionals \u2014 EP Program Manager",t:"security",w:"silentprofessionals.org/jobs/corporate-executive-protection-program-manager-chicago/",l:"Chicago, IL",co:"USA",p:"hot",n:"$165K/yr + bonus + benefits. Full-time. ACTIVE LISTING.",j:1},
{c:"Silent Professionals \u2014 EP Team Guatemala",t:"security",w:"silentprofessionals.org/jobs/executive-protection-team-guatemala/",l:"Guatemala",co:"Guatemala",p:"hot",n:"$700/day + expenses. Contract. ACTIVE LISTING.",j:1},
{c:"Silent Professionals \u2014 Armed EP Rotational",t:"security",w:"silentprofessionals.org/jobs/armed-executive-protection-houston-tx-rotational/",l:"Houston, TX",co:"USA",p:"hot",n:"$600/day. 90-day rotations. ACTIVE LISTING.",j:1},
{c:"Silent Professionals \u2014 EP Cartagena",t:"security",w:"silentprofessionals.org/jobs/executive-protection-cartagena-columbia/",l:"Cartagena",co:"Colombia",p:"hot",n:"$450-650/day + expenses. Contract. ACTIVE LISTING.",j:1},
{c:"Silent Professionals \u2014 Solo EP Agent",t:"security",w:"silentprofessionals.org/jobs/experienced-solo-ep-agent-el-salvador/",l:"El Salvador",co:"El Salvador",p:"hot",n:"$800/day + expenses. Contract. ACTIVE LISTING.",j:1},
{c:"Silent Professionals \u2014 Covert Protection",t:"security",w:"silentprofessionals.org/jobs/covert-ep-agent-argentina/",l:"Argentina",co:"Argentina",p:"hot",n:"$700/day + expenses. Contract. ACTIVE LISTING.",j:1},
{c:"Silent Professionals \u2014 Residential Security",t:"security",w:"silentprofessionals.org/jobs/residential-security-specialist-boca-raton-fl/",l:"Boca Raton, FL",co:"USA",p:"hot",n:"$570/day + full benefits. ACTIVE LISTING.",j:1},
{c:"Silent Professionals \u2014 EP East Asia",t:"security",w:"silentprofessionals.org/jobs/protection-agents-liaisons-east-asia/",l:"East Asia",co:"Asia",p:"hot",n:"$600-1,400/day + bonus. Contract. ACTIVE LISTING.",j:1},
{c:"Silent Professionals \u2014 Counter Surveillance NYC",t:"security",w:"silentprofessionals.org/jobs/armed-protective-counter-surveillance-nyc/",l:"New York City",co:"USA",p:"hot",n:"$1,000/day + expenses. Contract. ACTIVE LISTING.",j:1},
{c:"Silent Professionals \u2014 Director of Security",t:"security",w:"silentprofessionals.org/jobs/director-of-security-washington-dc/",l:"Washington, DC",co:"USA",p:"hot",n:"$130-160K/yr + bonus. Full-time. ACTIVE LISTING.",j:1},
{c:"Silent Professionals \u2014 PSD Ghana",t:"security",w:"silentprofessionals.org/jobs/psd-team-west-africa/",l:"Ghana",co:"Ghana",p:"hot",n:"$1,100/day + expenses. Contract. ACTIVE LISTING.",j:1},
{c:"Silent Professionals \u2014 Maritime Anti-Piracy",t:"security",w:"silentprofessionals.org/jobs/maritime-security-operators-anti-piracy/",l:"Global",co:"International",p:"hot",n:"$2,000/day! Contract. ACTIVE LISTING.",j:1},
{c:"GDBA \u2014 Security Specialist (IMMEDIATE)",t:"security",w:"grnh.se/67689ac71us",l:"Los Angeles, CA",co:"USA",p:"hot",n:"Gavin de Becker. IMMEDIATE NEED. Gold standard EP. ACTIVE LISTING.",j:1},
{c:"GDBA \u2014 Security Specialist (IMMEDIATE)",t:"security",w:"grnh.se/5f6d6ed81us",l:"Menlo Park, CA",co:"USA",p:"hot",n:"Gavin de Becker. IMMEDIATE NEED. ACTIVE LISTING.",j:1},
{c:"GDBA \u2014 Security Specialist (IMMEDIATE)",t:"security",w:"grnh.se/7ced4e321us",l:"Santa Barbara, CA",co:"USA",p:"hot",n:"Gavin de Becker. IMMEDIATE NEED. ACTIVE LISTING.",j:1},
{c:"GDBA \u2014 Security Specialist (IMMEDIATE)",t:"security",w:"grnh.se/4ab1b1d61us",l:"Maui, HI",co:"USA",p:"hot",n:"Gavin de Becker. IMMEDIATE NEED. ACTIVE LISTING.",j:1},
{c:"GDBA \u2014 Security Specialist (IMMEDIATE)",t:"security",w:"grnh.se/9kyhyeo01us",l:"Baltimore, MD",co:"USA",p:"hot",n:"Gavin de Becker. IMMEDIATE NEED. ACTIVE LISTING.",j:1},
{c:"GDBA \u2014 Security Specialist",t:"security",w:"grnh.se/a047dd3c1us",l:"Manhattan, NY",co:"USA",p:"hot",n:"Gavin de Becker. ACTIVE LISTING.",j:1},
{c:"GDBA \u2014 Security Specialist",t:"security",w:"grnh.se/166909ec1us",l:"Washington, DC",co:"USA",p:"hot",n:"Gavin de Becker. ACTIVE LISTING.",j:1},
{c:"GDBA \u2014 Security Specialist",t:"security",w:"grnh.se/48e311d61us",l:"Miami, FL",co:"USA",p:"hot",n:"Gavin de Becker. ACTIVE LISTING.",j:1},
{c:"GDBA \u2014 Field Travel Protector",t:"security",w:"grnh.se/7c0tguea1us",l:"Major US metros",co:"USA",p:"hot",n:"Gavin de Becker. Travel-based EP. ACTIVE LISTING.",j:1},
{c:"GardaWorld \u2014 Diplomatic CPO",t:"security",w:"jobs.garda.com/job/Baghdad-Diplomatic-Close-Protection-Officer-Iraq/890490900/",l:"Baghdad +4",co:"Iraq",p:"hot",n:"Diplomatic CP. International. ACTIVE LISTING.",j:1},
{c:"Morgan Stanley \u2014 EP Director (EMEA)",t:"security",w:"jobs.wallstreetfriends.org/companies/morgan-stanley/jobs/72296996",l:"London",co:"UK",p:"hot",n:"Director-level Executive Protection. EMEA. ACTIVE LISTING.",j:1},
{c:"Duke & Duchess Intl \u2014 CP Operative",t:"security",w:"dukeandduchess-int.com/jobs/full-time-close-protection-operative-live-out-ld433/",l:"Knightsbridge, London",co:"UK",p:"hot",n:"\u00a355-60K/yr. Full-time, live out. ACTIVE LISTING.",j:1},
{c:"Concentric \u2014 Chief of Security",t:"security",w:"job-boards.greenhouse.io/concentric/jobs/4595914006",l:"Global",co:"UK",p:"hot",n:"EP & Global Operations. ACTIVE LISTING.",j:1},
{c:"Guildhall \u2014 CPO/Executive Bodyguard",t:"security",w:"gulftalent.com/uae/jobs/close-protection-officer-executive-body-guard-397224",l:"Dubai",co:"UAE",p:"hot",n:"UHNW client. Seeks Western European. Live-in. ACTIVE LISTING.",j:1},
{c:"AHS \u2014 VIP CPO / Travelling Butler",t:"security",w:"gulftalent.com/uae/jobs/vip-close-protection-officer-travelling-butler-566249",l:"Dubai",co:"UAE",p:"hot",n:"VIP Close Protection + Butler role. ACTIVE LISTING.",j:1},
{c:"Allied Universal \u2014 EP Agent",t:"security",w:"linkedin.com/jobs/view/4411421740",l:"Arlington, VA",co:"USA",p:"hot",n:"$115K/yr. ACTIVE LISTING via LinkedIn.",j:1},
{c:"Gilead Sciences \u2014 Assoc Director EP",t:"security",w:"linkedin.com/jobs/view/4381760885",l:"San Francisco",co:"USA",p:"hot",n:"Senior/strategic role. ACTIVE LISTING via LinkedIn.",j:1},
{c:"ByteDance \u2014 EP Specialist",t:"security",w:"linkedin.com/jobs/view/4409967614",l:"Singapore",co:"Singapore",p:"hot",n:"Tech giant. High salary. ACTIVE LISTING via LinkedIn.",j:1},
{c:"Crisis24 \u2014 EP Senior Team Leader",t:"security",w:"linkedin.com/jobs/view/4409525543",l:"Menlo Park, CA",co:"USA",p:"hot",n:"Senior Team Leader. ACTIVE LISTING via LinkedIn.",j:1},
{c:"Constellis \u2014 EP Agents",t:"security",w:"linkedin.com/jobs/view/4407964725",l:"San Francisco",co:"USA",p:"hot",n:"Multiple locations (SF, Seattle, Montreal, Miami). ACTIVE LISTING via LinkedIn.",j:1},
{c:"NATO \u2014 Chief Agency Security Officer",t:"security",w:"impactpool.org/jobs/1191340",l:"Brussels",co:"Belgium",p:"hot",n:"NATO HQ. ACTIVE LISTING.",j:1},
{c:"Interpol \u2014 Security Ops Centre Manager",t:"security",w:"impactpool.org/jobs/891603",l:"Lyon",co:"France",p:"medium",n:"Interpol HQ. ACTIVE LISTING.",j:1},
{c:"Amazon \u2014 EP Manager, Protective Services",t:"security",w:"https://www.indeed.com/viewjob?jk=f2e60beaf9cb1409",l:"Seattle, WA",co:"USA",p:"hot",n:"Executive Protection Manager. Amazon. ACTIVE LISTING via Indeed.",j:1},
{c:"PayPal \u2014 Sr. Manager, EP Agent",t:"security",w:"https://www.indeed.com/viewjob?jk=19ba285d5cecf297",l:"San Jose, CA",co:"USA",p:"hot",n:"Senior Manager level EP. Hybrid. PayPal. ACTIVE LISTING via Indeed.",j:1},
{c:"HP \u2014 EP Specialist",t:"security",w:"https://www.indeed.com/viewjob?jk=2386d21eb693edab",l:"Palo Alto, CA",co:"USA",p:"hot",n:"Executive Protection Specialist. HP. ACTIVE LISTING via Indeed.",j:1},
{c:"Global Guardian \u2014 EP Agent / Security Driver",t:"security",w:"https://www.indeed.com/viewjob?jk=6a6dfa19dcfa9f76",l:"New Canaan, CT",co:"USA",p:"hot",n:"EP Agent + Security Driver combo. Global Guardian. ACTIVE LISTING via Indeed.",j:1},
{c:"Brookings Institution \u2014 Director of Safety & Security",t:"security",w:"https://www.indeed.com/viewjob?jk=799d42590a2ae465",l:"Washington, DC",co:"USA",p:"hot",n:"Director level. Think tank. ACTIVE LISTING via Indeed.",j:1},
];
